version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: daily
    commit-message:
      prefix: fix
      prefix-development: chore
      include: scope
    versioning-strategy: increase # Update package.json too
    groups:
      patterns:
        update-types:
          - patch
          - minor